import express from 'express';
import mappingRouter from './mapping.js';
import hostsRouter from './hosts.js';
import servicesRouter from './services.js';
import availabilityRouter from './availability.js';
import metricsRouter from './metrics.js';
import eventsRouter from './events.js';
import notificationsRouter from './notifications.js';
import reportPeriodRouter from './reportPeriod.js';
import saveJobsSyncRouter from './saveJobsSync.js';
import equipmentMonitoringSyncRouter from './equipmentMonitoringSync.js';
import checkmkWebhookRouter from './webhook.js';
const router = express.Router();
router.use('/', mappingRouter);
router.use('/', hostsRouter);
router.use('/', servicesRouter);
router.use('/', availabilityRouter);
router.use('/', metricsRouter);
router.use('/', eventsRouter);
router.use('/', notificationsRouter);
router.use('/', reportPeriodRouter);
router.use('/', saveJobsSyncRouter);
router.use('/', equipmentMonitoringSyncRouter);
router.use('/', checkmkWebhookRouter);
export default router;
